"""Regenerate booking_prompt_rules_body.py from booking_prompt.py (optional maintenance)."""
import json
import re
from pathlib import Path

HERE = Path(__file__).resolve().parent


def main() -> None:
    t = (HERE / "booking_prompt.py").read_text(encoding="utf-8")
    anchor = 'estado_str = " | ".join(estado) if estado else "início do fluxo"'
    i = t.index(anchor)
    j = t.index('return f"""', i)
    start = j + len('return f"""')
    end = t.index('"""', start)
    body = t[start:end]

    body = body.replace("{build_booking_tools_preamble(phone_hint)}", "__TOOLS_PREAMBLE__")
    body = body.replace("{hours_lines}", "__HOURS_LINES__")
    body = body.replace("{estado_str}", "__ESTADO_STR__")
    body = body.replace("{pet_rule}", "__PET_RULE__")
    body = body.replace("{PROACTIVITY_SCHEDULING_BLOCK}", "__PROACTIVITY__")
    body = body.replace("{PASSO_2_PET_SHARED_BLOCK}", "__PASSO2__")
    body = body.replace('{date_hint or "?"}', "__DATE_HINT_OR_Q__")
    body = body.replace('{selected_time or "?"}', "__SELECTED_TIME_OR_Q__")
    body = body.replace('{selected_time or "selecionado"}', "__SELECTED_TIME_OR_SEL__")

    # Header (per-turn) — remove from rules body; rebuilt at end of prompt
    idx_escopo = body.index("━━━ ESCOPO DESTE AGENTE ━━━")
    header_template = body[:idx_escopo]
    rules_only = body[idx_escopo:]

    header_template = (
        header_template.replace("{assistant_name}", "__ASSISTANT_NAME__")
        .replace("{company_name}", "__COMPANY_NAME__")
        .replace("{today}", "__TODAY__")
        .replace("{today_weekday}", "__TODAY_WEEKDAY__")
        .replace("{cal_weekday_block}", "__CAL_WEEKDAY_BLOCK__")
        .replace('{f"Cliente: {client_name}" if client_name else ""}', "__CLIENT_LINE__")
        .replace('{f"ESTÁGIO CRM: {client_stage}" if client_stage else ""}', "__CRM_LINE__")
        .replace(
            "«Cliente:» acima (cadastro do petshop)",
            "«Cliente:» no bloco CONTEXTO ao final deste prompt (cadastro do petshop)",
        )
    )

    for name, s in [
        ("header_template", header_template),
        ("rules_only", rules_only),
    ]:
        bad = re.findall(r"(?<!\{)\{[a-z_][a-z0-9_.]*\}", s)
        if bad:
            raise SystemExit(f"{name} unresolved: {bad[:20]}")

    out = HERE / "booking_prompt_rules_body.py"
    out.write_text(
        "# Generated by extract_booking_segments.py\n"
        "BOOKING_HEADER_TEMPLATE = "
        + json.dumps(header_template, ensure_ascii=False)
        + "\n\nBOOKING_RULES_BODY_TEMPLATE = "
        + json.dumps(rules_only, ensure_ascii=False)
        + "\n",
        encoding="utf-8",
    )
    print("Wrote", out, len(header_template), len(rules_only))


if __name__ == "__main__":
    main()
