"""One-off / regen: extracts static segments from router_prompt.py for prefix caching."""
import json
import re
from pathlib import Path

HERE = Path(__file__).resolve().parent


def main() -> None:
    t = (HERE / "router_prompt.py").read_text(encoding="utf-8")
    start = t.index('return f"""') + len('return f"""')
    end = t.rindex('"""')
    body = t[start:end]
    body = body.replace("{{", "{")

    i = body.index("━━━ REFERÊNCIA DE DATAS ━━━")
    j = body.index("━━━ CRÍTICO — CADASTRO ≠ escalation_agent ━━━")
    static_a = body[:i]
    context_template = body[i:j]
    static_b = body[j:]

    context_template = (
        context_template.replace(
            "Hoje: {today_display} ({today_weekday})",
            "Hoje: __TODAY_DISPLAY__ (__TODAY_WEEKDAY__)",
        )
        .replace(
            "Estágio atual no CRM: {client_stage}",
            "Estágio atual no CRM: __CLIENT_STAGE__",
        )
        .replace("{next_days}", "__NEXT_DAYS__")
        .replace("{cal_extra}{cal_weekday_rule}", "__CAL_BLOCK__")
        .replace('{services or "nenhum"}', "__SERVICES_LINE__")
        .replace("{cadastro_servicos}", "__CADASTRO_SERVICOS__")
        .replace("{cadastro_lodging}", "__CADASTRO_LODGING__")
    )

    static_b = (
        static_b.replace("{tomorrow_iso}", "__TOMORROW_ISO__")
        .replace("{next_monday_in_week}", "__NEXT_MONDAY_IN_WEEK__")
        .replace("{today.year}", "__YEAR__")
        .replace("{today.month:02d}", "__MONTH02__")
        .replace("{today_display}", "__TODAY_DISPLAY__")
        .replace("{next_friday.isoformat()}", "__NEXT_FRIDAY_ISO__")
    )

    bad = re.findall(r"(?<!\{)\{[a-z_][a-z0-9_.:]*\}", static_a + static_b + context_template)
    if bad:
        raise SystemExit(f"Unresolved brace patterns: {bad[:30]}")

    out = HERE / "router_prompt_segments.py"
    out.write_text(
        "# Generated by extract_router_segments.py — static-first router pieces.\n"
        "ROUTER_STATIC_A = "
        + json.dumps(static_a, ensure_ascii=False)
        + "\n\nROUTER_CONTEXT_TEMPLATE = "
        + json.dumps(context_template, ensure_ascii=False)
        + "\n\nROUTER_STATIC_B_TEMPLATE = "
        + json.dumps(static_b, ensure_ascii=False)
        + "\n",
        encoding="utf-8",
    )
    print("Wrote", out, "sizes", len(static_a), len(context_template), len(static_b))


if __name__ == "__main__":
    main()
